GitHub ACtions update

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -9,7 +9,7 @@ name: MekHQ CI with Gradle
 # Pull Requests being added/updated against master.
 on:
   pull_request:
-    branches: [ master ]
+    branches: [master]
 
 # Setup the Build Scan "VCS" link for all gradle invocations
 env:
@@ -23,172 +23,172 @@ jobs:
     # Run this job once for each combination in the matrix below.
     strategy:
       matrix:
-        os: [ ubuntu-latest ] # For CI/CD running on *nix is sufficient
-        java-distribution: [ temurin ]
-        java-version: [ 11, 17 ]
+        os: [ubuntu-latest] # For CI/CD running on *nix is sufficient
+        java-distribution: [temurin]
+        java-version: [17]
       fail-fast: false
 
     steps:
-    # Checkout the Pull Request source and put it in: ./mekhq
-    - uses: actions/checkout@v4
-      with:
-        path: mekhq
+      # Checkout the Pull Request source and put it in: ./mekhq
+      - uses: actions/checkout@v4
+        with:
+          path: mekhq
 
-    # Setup composite build for MekHQ
-    # See: https://github.com/MegaMek/megamek/wiki/Working-With-Gradle
-# Disabled - 25-Jun-2022 - Causing regular build failures and . 
-#    - name: Setup Composite Build for MekHQ
-#      run: |
-#        echo "includeBuild '../megamek'" >./mekhq/settings_local.gradle
-#        echo "includeBuild '../megameklab'" >>./mekhq/settings_local.gradle
+      # Setup composite build for MekHQ
+      # See: https://github.com/MegaMek/megamek/wiki/Working-With-Gradle
+      # Disabled - 25-Jun-2022 - Causing regular build failures and .
+      #    - name: Setup Composite Build for MekHQ
+      #      run: |
+      #        echo "includeBuild '../megamek'" >./mekhq/settings_local.gradle
+      #        echo "includeBuild '../megameklab'" >>./mekhq/settings_local.gradle
 
-    # Find the repo and branch to use for MM
-    #
-    # Output variables:
-    #
-    #    - mmRepo: The MM repository to use.
-    #    - mmBranch: The MM branch to use.
-#    - name: Find the Right MegaMek Branch
-#      id: find_mm
+      # Find the repo and branch to use for MM
+      #
+      # Output variables:
+      #
+      #    - mmRepo: The MM repository to use.
+      #    - mmBranch: The MM branch to use.
+      #    - name: Find the Right MegaMek Branch
+      #      id: find_mm
       # Override bash so that it doesn't fail fast (the default)
       # if we can't find the branch
-#      shell: bash {0}
+      #      shell: bash {0}
       # This shell script searches the PR submitter's MM repo for
       # a branch that has the same name as the current PR branch.
       # If found it sets the `mmRepo` and `mmBranch` step output variables
       # to that branch.
-#      run: |
-#        git ls-remote --exit-code --heads ${{ github.event.pull_request.head.repo.owner.html_url }}/megamek.git ${{ github.event.pull_request.head.ref }}
-#        if [ "$?" == "0" ]
-#        then
-#          echo "${{ github.event.pull_request.head.repo.owner.html_url }}" | awk -F/ '{print "::set-output name=mmRepo::" $4 "/megamek"}'
-#          echo "::set-output name=mmBranch::${{ github.event.pull_request.head.ref }}"
-#        else
-#          echo "::set-output name=mmRepo::MegaMek/megamek"
-#          echo "::set-output name=mmBranch::master"
-#        fi
-#        exit 0
+      #      run: |
+      #        git ls-remote --exit-code --heads ${{ github.event.pull_request.head.repo.owner.html_url }}/megamek.git ${{ github.event.pull_request.head.ref }}
+      #        if [ "$?" == "0" ]
+      #        then
+      #          echo "${{ github.event.pull_request.head.repo.owner.html_url }}" | awk -F/ '{print "::set-output name=mmRepo::" $4 "/megamek"}'
+      #          echo "::set-output name=mmBranch::${{ github.event.pull_request.head.ref }}"
+      #        else
+      #          echo "::set-output name=mmRepo::MegaMek/megamek"
+      #          echo "::set-output name=mmBranch::master"
+      #        fi
+      #        exit 0
 
-    # Checkout the latest MegaMek source and put it in: ./megamek
-    - name: Checkout MegaMek
-      uses: actions/checkout@v4
-      with:
-#        repository: ${{ steps.find_mm.outputs.mmRepo }}
-#        ref:  ${{ steps.find_mm.outputs.mmBranch }}
-        repository: MegaMek/megamek
-        path: megamek
+      # Checkout the latest MegaMek source and put it in: ./megamek
+      - name: Checkout MegaMek
+        uses: actions/checkout@v4
+        with:
+          #        repository: ${{ steps.find_mm.outputs.mmRepo }}
+          #        ref:  ${{ steps.find_mm.outputs.mmBranch }}
+          repository: MegaMek/megamek
+          path: megamek
 
-    # Find the repo and branch to use for MML
-    #
-    # Output variables:
-    #
-    #    - mmlRepo: The MML repository to use.
-    #    - mmlBranch: The MML branch to use.
-#    - name: Find the Right MegaMekLab Branch
-#      id: find_mml
+      # Find the repo and branch to use for MML
+      #
+      # Output variables:
+      #
+      #    - mmlRepo: The MML repository to use.
+      #    - mmlBranch: The MML branch to use.
+      #    - name: Find the Right MegaMekLab Branch
+      #      id: find_mml
       # Override bash so that it doesn't fail fast (the default)
       # if we can't find the branch
-#      shell: bash {0}
+      #      shell: bash {0}
       # This shell script searches the PR submitter's MML repo for
       # a branch that has the same name as the current PR branch.
       # If found it sets the mmlRepo and mmlBranch step output variables
       # to that branch.
-#      run: |
-#        git ls-remote --exit-code --heads ${{ github.event.pull_request.head.repo.owner.html_url }}/megameklab.git ${{ github.event.pull_request.head.ref }}
-#        if [ "$?" == "0" ]
-#        then
-#          echo "${{ github.event.pull_request.head.repo.owner.html_url }}" | awk -F/ '{print "::set-output name=mmlRepo::" $4 "/megameklab"}'
-#          echo "::set-output name=mmlBranch::${{ github.event.pull_request.head.ref }}"
-#        else
-#          echo "::set-output name=mmlRepo::MegaMek/megameklab"
-#          echo "::set-output name=mmlBranch::master"
-#        fi
-#        exit 0
+      #      run: |
+      #        git ls-remote --exit-code --heads ${{ github.event.pull_request.head.repo.owner.html_url }}/megameklab.git ${{ github.event.pull_request.head.ref }}
+      #        if [ "$?" == "0" ]
+      #        then
+      #          echo "${{ github.event.pull_request.head.repo.owner.html_url }}" | awk -F/ '{print "::set-output name=mmlRepo::" $4 "/megameklab"}'
+      #          echo "::set-output name=mmlBranch::${{ github.event.pull_request.head.ref }}"
+      #        else
+      #          echo "::set-output name=mmlRepo::MegaMek/megameklab"
+      #          echo "::set-output name=mmlBranch::master"
+      #        fi
+      #        exit 0
 
-    # Checkout the latest MegaMekLab source and put it in: ./megameklab
-    - name: Checkout MegaMekLab
-      uses: actions/checkout@v4
-      with:
-#        repository: ${{ steps.find_mml.outputs.mmlRepo }}
-#        ref: ${{ steps.find_mml.outputs.mmlBranch }}
-        repository: MegaMek/megameklab
-        path: megameklab
+      # Checkout the latest MegaMekLab source and put it in: ./megameklab
+      - name: Checkout MegaMekLab
+        uses: actions/checkout@v4
+        with:
+          #        repository: ${{ steps.find_mml.outputs.mmlRepo }}
+          #        ref: ${{ steps.find_mml.outputs.mmlBranch }}
+          repository: MegaMek/megameklab
+          path: megameklab
 
-    # Setup composite build for MegaMekLab
-    # See: https://github.com/MegaMek/megamek/wiki/Working-With-Gradle
-#    - name: Setup Composite Build for MegaMekLab
-#      run: |
-#        echo "if (gradle.parent == null) includeBuild '../megamek'" >./megameklab/settings_local.gradle
+      # Setup composite build for MegaMekLab
+      # See: https://github.com/MegaMek/megamek/wiki/Working-With-Gradle
+      #    - name: Setup Composite Build for MegaMekLab
+      #      run: |
+      #        echo "if (gradle.parent == null) includeBuild '../megamek'" >./megameklab/settings_local.gradle
 
-    # Setup the requested Java Distribution and Version from the matrix
-    - name: Set up ${{ matrix.java-distribution }} JDK ${{ matrix.java-version }}
-      uses: actions/setup-java@v4
-      with:
-        distribution: ${{ matrix.java-distribution }}
-        java-version: ${{ matrix.java-version }}
+      # Setup the requested Java Distribution and Version from the matrix
+      - name: Set up ${{ matrix.java-distribution }} JDK ${{ matrix.java-version }}
+        uses: actions/setup-java@v4
+        with:
+          distribution: ${{ matrix.java-distribution }}
+          java-version: ${{ matrix.java-version }}
 
-    # Make sure we can execute the Gradle wrapper
-    - name: Grant execute permission for gradlew (*nix or MacOS)
-      working-directory: mekhq
-      run: chmod +x gradlew
-      if: runner.os != 'Windows'
+      # Make sure we can execute the Gradle wrapper
+      - name: Grant execute permission for gradlew (*nix or MacOS)
+        working-directory: mekhq
+        run: chmod +x gradlew
+        if: runner.os != 'Windows'
 
-    # Build the MekHQ project
-    #
-    # Directory layout:
-    #    /mekhq
-    #        /gradlew
-    #    /megamek
-    #    /megameklab
-    #
-    # Output Variables:
-    #    - buildScanUri
-    - name: Build with Gradle
-      uses: gradle/actions/setup-gradle@v3
-      with:
-        arguments: clean build --no-build-cache --info --continue --stacktrace --max-workers=1 --scan
-        build-root-directory: mekhq
+      # Build the MekHQ project
+      #
+      # Directory layout:
+      #    /mekhq
+      #        /gradlew
+      #    /megamek
+      #    /megameklab
+      #
+      # Output Variables:
+      #    - buildScanUri
+      - name: Build with Gradle
+        uses: gradle/actions/setup-gradle@v3
+        with:
+          arguments: clean build --no-build-cache --info --continue --stacktrace --max-workers=1 --scan
+          build-root-directory: mekhq
 
-    # If the build step fails, try to upload any test logs in case it was a unit test failure.
-    # The logs will be relative to the ./mekhq directory.
-#    - name: Upload Test Logs on Failure
-#      uses: actions/upload-artifact@v3
-#      if: failure()
-#      with:
-#        name: cd-failure-logs
-#        path: ./mekhq/MekHQ/build/reports/
+      # If the build step fails, try to upload any test logs in case it was a unit test failure.
+      # The logs will be relative to the ./mekhq directory.
+      #    - name: Upload Test Logs on Failure
+      #      uses: actions/upload-artifact@v3
+      #      if: failure()
+      #      with:
+      #        name: cd-failure-logs
+      #        path: ./mekhq/MekHQ/build/reports/
 
-    # Upload our Code Coverage Reports to CodeCov.io
-    - name: CodeCov.io Coverage Report
-      uses: codecov/codecov-action@v3
-      with:
-        directory: ./mekhq/MekHQ/build/reports/jacoco/test
-        fail_ci_if_error: false
-        verbose: true
+      # Upload our Code Coverage Reports to CodeCov.io
+      - name: CodeCov.io Coverage Report
+        uses: codecov/codecov-action@v3
+        with:
+          directory: ./mekhq/MekHQ/build/reports/jacoco/test
+          fail_ci_if_error: false
+          verbose: true
 
-    # If we have a buildScanUri comment on the PR
-    #
-    # NB: This only works if you're on the main MegaMek\mekhq repo
-    #     for now due to a GitHub Actions limitation.
-# CAW: temporarily halted https://github.com/thollander/actions-comment-pull-request/issues/17
-#    - name: Comment on PR with Build Scan URI
-#      uses: thollander/actions-comment-pull-request@master
-#      if: always() && steps.gradle_build.outputs.buildScanUri != ''
-#      with:
-#        message: Build scan available at ${{ steps.gradle_build.outputs.buildScanUri }}
-#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      # If we have a buildScanUri comment on the PR
+      #
+      # NB: This only works if you're on the main MegaMek\mekhq repo
+      #     for now due to a GitHub Actions limitation.
+      # CAW: temporarily halted https://github.com/thollander/actions-comment-pull-request/issues/17
+      #    - name: Comment on PR with Build Scan URI
+      #      uses: thollander/actions-comment-pull-request@master
+      #      if: always() && steps.gradle_build.outputs.buildScanUri != ''
+      #      with:
+      #        message: Build scan available at ${{ steps.gradle_build.outputs.buildScanUri }}
+      #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-    # Put the Windows Release in an artifact
-    # NB: Due to a GitHub Actions limitation we won't know what the filename is in order to display it somewhere.
-    - name: Upload Windows Release
-      uses: actions/upload-artifact@v4
-      with:
-        name: mhq-release-win-${{ matrix.java-distribution }}-jdk${{ matrix.java-version }}
-        path: ./mekhq/MekHQ/build/distributions/mekhq-windows-*.zip
+      # Put the Windows Release in an artifact
+      # NB: Due to a GitHub Actions limitation we won't know what the filename is in order to display it somewhere.
+      - name: Upload Windows Release
+        uses: actions/upload-artifact@v4
+        with:
+          name: mhq-release-win-${{ matrix.java-distribution }}-jdk${{ matrix.java-version }}
+          path: ./mekhq/MekHQ/build/distributions/mekhq-windows-*.zip
 
-    # Put the non-Windows release in an artifact
-    - name: Upload Nix/Mac Release
-      uses: actions/upload-artifact@v4
-      with:
-        name: mhq-release-nix-mac-${{ matrix.java-distribution }}-jdk${{ matrix.java-version }}
-        path: ./mekhq/MekHQ/build/distributions/*.tar
+      # Put the non-Windows release in an artifact
+      - name: Upload Nix/Mac Release
+        uses: actions/upload-artifact@v4
+        with:
+          name: mhq-release-nix-mac-${{ matrix.java-distribution }}-jdk${{ matrix.java-version }}
+          path: ./mekhq/MekHQ/build/distributions/*.tar.gz
