Initial work on CI Actions

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -20,6 +20,12 @@ jobs:
   ci_cd:
     runs-on: ${{ matrix.os }}
 
+    outputs:
+      mmRepo: ${{ steps.find_mm.outputs.mmRepo }}
+      mmBranch: ${{ steps.find_mm.outputs.mmBranch }}
+      mmlRepo: ${{ steps.find_mml.outputs.mmRepo }}
+      mmlBranch: ${{ steps.find_mml.outputs.mmBranch }}
+
     # Run this job once for each combination in the matrix below.
     strategy:
       matrix:
@@ -30,17 +36,18 @@ jobs:
 
     steps:
       # Checkout the Pull Request source and put it in: ./mekhq
-      - uses: actions/checkout@v4
+      - name: Checkout out MekHQ
+        uses: actions/checkout@v4
         with:
           path: mekhq
 
       # Setup composite build for MekHQ
       # See: https://github.com/MegaMek/megamek/wiki/Working-With-Gradle
       # Disabled - 25-Jun-2022 - Causing regular build failures and .
-      #    - name: Setup Composite Build for MekHQ
-      #      run: |
-      #        echo "includeBuild '../megamek'" >./mekhq/settings_local.gradle
-      #        echo "includeBuild '../megameklab'" >>./mekhq/settings_local.gradle
+      - name: Setup Composite Build for MekHQ
+        run: |
+          echo "includeBuild '../megamek'" >./mekhq/settings_local.gradle
+          echo "includeBuild '../megameklab'" >>./mekhq/settings_local.gradle
 
       # Find the repo and branch to use for MM
       #
@@ -48,34 +55,32 @@ jobs:
       #
       #    - mmRepo: The MM repository to use.
       #    - mmBranch: The MM branch to use.
-      #    - name: Find the Right MegaMek Branch
-      #      id: find_mm
-      # Override bash so that it doesn't fail fast (the default)
-      # if we can't find the branch
-      #      shell: bash {0}
-      # This shell script searches the PR submitter's MM repo for
-      # a branch that has the same name as the current PR branch.
-      # If found it sets the `mmRepo` and `mmBranch` step output variables
-      # to that branch.
-      #      run: |
-      #        git ls-remote --exit-code --heads ${{ github.event.pull_request.head.repo.owner.html_url }}/megamek.git ${{ github.event.pull_request.head.ref }}
-      #        if [ "$?" == "0" ]
-      #        then
-      #          echo "${{ github.event.pull_request.head.repo.owner.html_url }}" | awk -F/ '{print "::set-output name=mmRepo::" $4 "/megamek"}'
-      #          echo "::set-output name=mmBranch::${{ github.event.pull_request.head.ref }}"
-      #        else
-      #          echo "::set-output name=mmRepo::MegaMek/megamek"
-      #          echo "::set-output name=mmBranch::master"
-      #        fi
-      #        exit 0
+      - name: Find the Right MegaMek Branch
+        id: find_mm
+        # Override bash so that it doesn't fail fast (the default) if we can't find the branch
+        shell: bash {0}
+        # This shell script searches the PR submitter's MM repo for
+        # a branch that has the same name as the current PR branch.
+        # If found it sets the `mmRepo` and `mmBranch` step output variables
+        # to that branch.
+        run: |
+          git ls-remote --exit-code --heads ${{ github.event.pull_request.head.repo.owner.html_url }}/megamek.git ${{ github.event.pull_request.head.ref }}
+          if [ "$?" == "0" ]
+          then
+            echo "mmRepo=${{ github.event.pull_request.head.repo.owner.login }}/megamek" >> $GITHUB_OUTPUT
+            echo "mmBranch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
+          else
+            echo "mmRepo=MegaMek/megamek" >> $GITHUB_OUTPUT
+            echo "mmBranch=master" >> $GITHUB_OUTPUT
+          fi
+          exit 0
 
       # Checkout the latest MegaMek source and put it in: ./megamek
       - name: Checkout MegaMek
         uses: actions/checkout@v4
         with:
-          #        repository: ${{ steps.find_mm.outputs.mmRepo }}
-          #        ref:  ${{ steps.find_mm.outputs.mmBranch }}
-          repository: MegaMek/megamek
+          repository: ${{ steps.find_mm.outputs.mmRepo }}
+          ref: ${{ steps.find_mm.outputs.mmBranch }}
           path: megamek
 
       # Find the repo and branch to use for MML
@@ -84,41 +89,33 @@ jobs:
       #
       #    - mmlRepo: The MML repository to use.
       #    - mmlBranch: The MML branch to use.
-      #    - name: Find the Right MegaMekLab Branch
-      #      id: find_mml
-      # Override bash so that it doesn't fail fast (the default)
-      # if we can't find the branch
-      #      shell: bash {0}
-      # This shell script searches the PR submitter's MML repo for
-      # a branch that has the same name as the current PR branch.
-      # If found it sets the mmlRepo and mmlBranch step output variables
-      # to that branch.
-      #      run: |
-      #        git ls-remote --exit-code --heads ${{ github.event.pull_request.head.repo.owner.html_url }}/megameklab.git ${{ github.event.pull_request.head.ref }}
-      #        if [ "$?" == "0" ]
-      #        then
-      #          echo "${{ github.event.pull_request.head.repo.owner.html_url }}" | awk -F/ '{print "::set-output name=mmlRepo::" $4 "/megameklab"}'
-      #          echo "::set-output name=mmlBranch::${{ github.event.pull_request.head.ref }}"
-      #        else
-      #          echo "::set-output name=mmlRepo::MegaMek/megameklab"
-      #          echo "::set-output name=mmlBranch::master"
-      #        fi
-      #        exit 0
+      - name: Find the Right MegaMek Branch
+        id: find_mm
+        # Override bash so that it doesn't fail fast (the default) if we can't find the branch
+        shell: bash {0}
+        # This shell script searches the PR submitter's MM repo for
+        # a branch that has the same name as the current PR branch.
+        # If found it sets the `mmRepo` and `mmBranch` step output variables
+        # to that branch.
+        run: |
+          git ls-remote --exit-code --heads ${{ github.event.pull_request.head.repo.owner.html_url }}/megameklab.git ${{ github.event.pull_request.head.ref }}
+          if [ "$?" == "0" ]
+          then
+            echo "mmlRepo=${{ github.event.pull_request.head.repo.owner.login }}/megameklab" >> $GITHUB_OUTPUT
+            echo "mmlBranch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
+          else
+            echo "mmlRepo=MegaMek/megameklab" >> $GITHUB_OUTPUT
+            echo "mmlBranch=master" >> $GITHUB_OUTPUT
+          fi
+          exit 0
 
       # Checkout the latest MegaMekLab source and put it in: ./megameklab
       - name: Checkout MegaMekLab
         uses: actions/checkout@v4
         with:
-          #        repository: ${{ steps.find_mml.outputs.mmlRepo }}
-          #        ref: ${{ steps.find_mml.outputs.mmlBranch }}
-          repository: MegaMek/megameklab
+          repository: ${{ steps.find_mml.outputs.mmlRepo }}
+          ref: ${{ steps.find_mml.outputs.mmlBranch }}
           path: megameklab
-
-      # Setup composite build for MegaMekLab
-      # See: https://github.com/MegaMek/megamek/wiki/Working-With-Gradle
-      #    - name: Setup Composite Build for MegaMekLab
-      #      run: |
-      #        echo "if (gradle.parent == null) includeBuild '../megamek'" >./megameklab/settings_local.gradle
 
       # Setup the requested Java Distribution and Version from the matrix
       - name: Set up ${{ matrix.java-distribution }} JDK ${{ matrix.java-version }}
diff --git a/.github/workflows/codeql-analysis.yml b/.github/workflows/codeql-analysis.yml
--- a/.github/workflows/codeql-analysis.yml
+++ b/.github/workflows/codeql-analysis.yml
@@ -24,6 +24,12 @@ jobs:
     name: Analyze
     runs-on: ${{ matrix.os }}
 
+    outputs:
+      mmRepo: ${{ steps.find_mm.outputs.mmRepo }}
+      mmBranch: ${{ steps.find_mm.outputs.mmBranch }}
+      mmlRepo: ${{ steps.find_mml.outputs.mmRepo }}
+      mmlBranch: ${{ steps.find_mml.outputs.mmBranch }}
+
     # Run this job once for each combination in the matrix below.
     strategy:
       matrix:
@@ -34,8 +40,86 @@ jobs:
       fail-fast: false
 
     steps:
-      - name: Checkout repository
+      - name: Checkout out MekHQ
         uses: actions/checkout@v4
+        with:
+          path: mekhq
+
+      # Setup composite build for MekHQ
+      # See: https://github.com/MegaMek/megamek/wiki/Working-With-Gradle
+      # Disabled - 25-Jun-2022 - Causing regular build failures and .
+      - name: Setup Composite Build for MekHQ
+        run: |
+          echo "includeBuild '../megamek'" >./mekhq/settings_local.gradle
+          echo "includeBuild '../megameklab'" >>./mekhq/settings_local.gradle
+
+      # Find the repo and branch to use for MM
+      #
+      # Output variables:
+      #
+      #    - mmRepo: The MM repository to use.
+      #    - mmBranch: The MM branch to use.
+      - name: Find the Right MegaMek Branch
+        id: find_mm
+        # Override bash so that it doesn't fail fast (the default) if we can't find the branch
+        shell: bash {0}
+        # This shell script searches the PR submitter's MM repo for
+        # a branch that has the same name as the current PR branch.
+        # If found it sets the `mmRepo` and `mmBranch` step output variables
+        # to that branch.
+        run: |
+          git ls-remote --exit-code --heads ${{ github.event.pull_request.head.repo.owner.html_url }}/megamek.git ${{ github.event.pull_request.head.ref }}
+          if [ "$?" == "0" ]
+          then
+            echo "mmRepo=${{ github.event.pull_request.head.repo.owner.login }}/megamek" >> $GITHUB_OUTPUT
+            echo "mmBranch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
+          else
+            echo "mmRepo=MegaMek/megamek" >> $GITHUB_OUTPUT
+            echo "mmBranch=master" >> $GITHUB_OUTPUT
+          fi
+          exit 0
+
+      # Checkout the latest MegaMek source and put it in: ./megamek
+      - name: Checkout MegaMek
+        uses: actions/checkout@v4
+        with:
+          repository: ${{ steps.find_mm.outputs.mmRepo }}
+          ref: ${{ steps.find_mm.outputs.mmBranch }}
+          path: megamek
+
+      # Find the repo and branch to use for MML
+      #
+      # Output variables:
+      #
+      #    - mmlRepo: The MML repository to use.
+      #    - mmlBranch: The MML branch to use.
+      - name: Find the Right MegaMek Branch
+        id: find_mm
+        # Override bash so that it doesn't fail fast (the default) if we can't find the branch
+        shell: bash {0}
+        # This shell script searches the PR submitter's MM repo for
+        # a branch that has the same name as the current PR branch.
+        # If found it sets the `mmRepo` and `mmBranch` step output variables
+        # to that branch.
+        run: |
+          git ls-remote --exit-code --heads ${{ github.event.pull_request.head.repo.owner.html_url }}/megameklab.git ${{ github.event.pull_request.head.ref }}
+          if [ "$?" == "0" ]
+          then
+            echo "mmlRepo=${{ github.event.pull_request.head.repo.owner.login }}/megameklab" >> $GITHUB_OUTPUT
+            echo "mmlBranch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
+          else
+            echo "mmlRepo=MegaMek/megameklab" >> $GITHUB_OUTPUT
+            echo "mmlBranch=master" >> $GITHUB_OUTPUT
+          fi
+          exit 0
+
+      # Checkout the latest MegaMekLab source and put it in: ./megameklab
+      - name: Checkout MegaMekLab
+        uses: actions/checkout@v4
+        with:
+          repository: ${{ steps.find_mml.outputs.mmlRepo }}
+          ref: ${{ steps.find_mml.outputs.mmlBranch }}
+          path: megameklab
 
       # Setup the requested Java Distribution and Version from the matrix
       - name: Set up ${{ matrix.java-distribution }} JDK ${{ matrix.java-version }}
@@ -55,21 +139,12 @@ jobs:
           # queries: ./path/to/local/query, your-org/your-repo/queries@main
           queries: +security-and-quality
 
-      # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
-      # If this step fails, then you should remove it and run the build manually (see below)
-      - name: Autobuild MekHQ
-        uses: github/codeql-action/autobuild@v3
+      - name: Setup Gradle
+        uses: gradle/actions/setup-gradle@v3
 
-      # ℹ️ Command-line programs to run using the OS shell.
-      # 📚 https://git.io/JvXDl
-
-      # ✏️ If the Autobuild fails above, remove it and uncomment the following three lines
-      #    and modify them (or add more) to build your code if your project
-      #    uses a compiled language
-
-      #- run: |
-      #   make bootstrap
-      #   make release
+      - name: Build with Gradle
+        working-directory: megameklab
+        run: ./gradlew build --stacktrace --scan
 
       - name: Perform CodeQL Analysis
         uses: github/codeql-action/analyze@v3
